openapi: 3.0.3
info:
  title: Category RESTfull API
  description: API Spec for Category RESTfull API
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api'
paths:
  /categories:
    get:
      tags:
        - Category API
      description: List All Categories
      summary: List All Categories
      security:
        - CategoryAuth: []
      responses:
        200:
          description: Success get all categories
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: "#/components/schemas/Category"
    post:
      tags:
        - Category API
      description: Create new category
      summary: Create new category
      security:
        - CategoryAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrUpdateCategory"
      responses:
        200:
          description: Success create category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/Category"
  /categories/{categoryId}:
    get:
      tags:
        - Category API
      summary: Get category by Id
      description: Get category by Id
      security:
        - CategoryAuth: [ ]
      parameters:
        - name: categoryId
          in: path
          description: Category Id
      responses:
        200:
          description: Success get category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/Category"
    put:
      tags:
        - Category API
      summary: Update category by Id
      description: Update category by Id
      security:
        - CategoryAuth: [ ]
      parameters:
        - name: categoryId
          in: path
          description: Category Id
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateOrUpdateCategory"
      responses:
        200:
          description: Success Update category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
                  data:
                    $ref: "#/components/schemas/Category"
    delete:
      tags:
        - Category API
      summary: Delete category by Id
      description: Delete category by Id
      security:
        - CategoryAuth: [ ]
      parameters:
        - name: categoryId
          in: path
          description: Category Id
      responses:
        200:
          description: Success delete category
          content:
            application/json:
              schema:
                type: object
                properties:
                  code:
                    type: number
                  status:
                    type: string
components:
  securitySchemes:
    CategoryAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: Authentication for Category API
  schemas:
    CreateOrUpdateCategory:
      type: object
      properties:
        name:
          type: string
    Category:
      type: object
      properties:
        id:
          type: number
        name:
          type: string